clone_depth: 5

version: "{build}"

environment:
  matrix:
    - NODEJS_VERSION: "8"
      PLATFORM: x86
    - NODEJS_VERSION: "8"
      PLATFORM: x64
    - NODEJS_VERSION: "10"
      PLATFORM: x64
    - NODEJS_VERSION: "12"
      PLATFORM: x64

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - npm ci

test_script:
  - node --version
  - npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - npm test

build: off

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache\ -> appveyor.yml,package.json,package-lock.json'
